const ALL_ADMIN_ROUTES = {
	admin_auth: require("../website/v1/routes/admin/auth"),
	admin_mailer: require("../website/v1/routes/admin/mailer"),
	admin_forgetpassword: require("../website/v1/routes/admin/forget.password"),
	admin_order: require("../website/v1/routes/admin/order"),
	admin_subscription: require("../website/v1/routes/admin/subscription"),
	admin_ticket: require("../website/v1/routes/admin/ticket"),
	admin_seller: require("../website/v1/routes/admin/seller"),
	admin_user: require("../website/v1/routes/admin/customer"),
	admin_search: require("../website/v1/routes/admin/search"),
	admin_dashboard: require("../website/v1/routes/admin/dashboard"),
	admin_language: require("../website/v1/routes/admin/language"),
	admin_product: require("../website/v1/routes/admin/product"),
	admin_productVariant: require("../website/v1/routes/admin/productVariant"),
	admin_customer: require("../website/v1/routes/admin/customer"),
	admin_currency: require("../website/v1/routes/admin/currency"),
	admin_currency_decimal: require("../website/v1/routes/admin/currency_decimal"),

	admin_category: require("../website/v1/routes/admin/category"),
	admin_cart: require("../website/v1/routes/admin/cart"),
	admin_wishlist: require("../website/v1/routes/admin/wishlist"),
	admin_policy: require("../website/v1/routes/admin/policy"),
	admin_suggestidea: require("../website/v1/routes/admin/suggestIdea"),
	admin_notification: require("../website/v1/routes/admin/notification"),
	admin_newsletter: require("../website/v1/routes/admin/newsLetter"),
	admin_adminroute: require("../website/v1/routes/admin/admin"),
	admin_brand: require("../website/v1/routes/admin/brand"),
	admin_reports: require("../website/v1/routes/admin/reports"),
	admin_coupon: require("./../website/v1/routes/admin/coupon"),
	admin_couponItem: require("./../website/v1/routes/admin/couponItem"),
	admin_whattopromote: require("./../website/v1/routes/common/whatToPromote"),
	admin_offerpricing: require("./../website/v1/routes/admin/offerPricing"),
	admin_offerpricingItem: require("./../website/v1/routes/admin/offerPricingItem"),
	admin_advertisement: require("./../website/v1/routes/admin/advertisementCampaign"),
	admin_advertiseCharges: require("./../website/v1/routes/admin/advertisementCharges"),
	admin_WhatToPromoteAPI: require("./../website/v1/routes/admin/whatToPromote"),
	admin_faq: require("./../website/v1/routes/common/faq"),
	admin_productReviews: require("./../website/v1/routes/admin/productReviews"),
	admin_productQuestions: require("./../website/v1/routes/admin/productQuestion"),
	admin_customerSellerMessage: require("./../website/v1/routes/admin/sellerCustomerMessage"),
	admin_settings: require("./../website/v1/routes/admin/settings"),
	admin_wallet: require("./../website/v1/routes/admin/wallet"),
	admin_invoice: require("./../website/v1/routes/common/invoice"),
};

module.exports = ALL_ADMIN_ROUTES;
