const ALL_ROUTES = {
    auth_route: require('./../routes/customer/auth'),
    customer_forgotPassword: require("./../routes/customer/forget.password"),
    brand_Route: require("./../routes/brand"),
    product_customer: require("./../routes/customer/product"),
    customer_route: require("./../routes/customer"),
    customer_brand: require("./../routes/customer/productvariant"),
    customer_productvariant_reviews: require("./../routes/customer/reviews"),
    customer_question: require("./../routes/customer/productVariantQuestion"),
    policyRoute: require("./../routes/policy_Route"),
    manageAddress_Route: require("./../routes/manageAddress"),
    category_Route: require("./../routes/customer/category"),
    customer_Cart: require("./../routes/customer/cartRoute"),
    customer_order: require("./../routes/customer/order"),
    newArrivalProducts: require("./../routes/customer/newArrival"),
    globalSearch: require("./../routes/customer/globalSearch"),
    wishlist: require("./../routes/customer/wishlist"),
    justsoldproducts: require("./../routes/customer/justSoldProducts"),
    trendingProducts: require("./../routes/customer/trendingProduct"),
    recommendedProducts: require("./../routes/customer/recommended"),
    saveForLetter: require("./../routes/customer/saveForLetter"),
    brandSellerFollowing: require('./../routes/customer/customerSellerFollowing'),
    brand_seller: require("./../routes/customer/brand"),
    customer_message: require("./../routes/customer/message"),
    contact: require("./../routes/customer/contactUs"),
    subscribeProduct: require('./../routes/customer/subscribeProduct'),
    languageRoute: require('./../routes/language'),
    offerRoute: require('./../routes/customer/offer'),
    currencyRateRoute: require('./../routes/customer/curencyRate'),
    suggetIdea: require('./../routes/customer/suggestIdea'),
    wallet: require('./../routes/customer/wallet'),
    app_notification: require('./../routes/customer/notification'),
    app_coupon: require('./../routes/customer/coupon'),
    app_similarProducts: require('./../routes/customer/similarProducts'),
    app_advertisement: require('./../routes/customer/advertisement'),
    app_faqs: require('./../routes/customer/faq'),
    app_notify: require('./../routes/customer/notify'),
    app_checkout: require("./../routes/customer/checkout"),
    app_customer_address: require("./../routes/customer/customerAddress"),
    app_AdClick: require('./../routes/customer/advertiseAnalytics'),
    app_Analytics: require('./../routes/customer/productAnalytics'),

}


module.exports = ALL_ROUTES;
